apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: helm-rook-ceph
spec:
  package: ghcr.io/hops-ops/helm-rook-ceph:{{ .Values.version }}
{{- if .Values.skipDependencyResolution }}
  skipDependencyResolution: true
{{- end }}
{{- if .Values.skipDependencyResolution }}
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: hops-ops-helm-rook-cephrender
spec:
  package: ghcr.io/hops-ops/helm-rook-cephrender:{{ .Values.version }}
{{- end }}
